voxelizer.cc:(.text+0x6): undefined reference to `void Die<char const*>(char const*)'
voxelizer.o: In function `main':
voxelizer.cc:(.text.startup+0x124): undefined reference to `void Die<char const*, double>(char const*, double)'
voxelizer.cc:(.text.startup+0x146): undefined reference to `void Die<char const*>(char const*)'
voxelizer.cc:(.text.startup+0x1e1): undefined reference to `void Die<char const*>(char const*)'
voxelizer.cc:(.text.startup+0x24a): undefined reference to `void Die<char const*, int, char*>(char const*, int, char*)'
voxelizer.cc:(.text.startup+0x27e): undefined reference to `void Die<char const*, int>(char const*, int)'
voxelizer.cc:(.text.startup+0x2ad): undefined reference to `void Die<char const*, int, char*>(char const*, int, char*)'
voxelizer.cc:(.text.startup+0x2f8): undefined reference to `void ParseFilename<unsigned char>(char*, std::vector<char*, std::allocator<char*> >&, std::vector<unsigned char, std::allocator<unsigned char> >&)'
voxelizer.cc:(.text.startup+0x42a): undefined reference to `void Die<char const*>(char const*)'
voxelizer.cc:(.text.startup+0x51e): undefined reference to `PNG<1>::Pixel* ZSlice<PNG<1>::Pixel>(PNG<1>::Pixel*, unsigned long, unsigned long, unsigned long)'
